# Module not found: Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors
# @link: https://github.com/esxjs/esx/issues/18
packageExtensions:
  "vite@*":
    dependencies:
      "supports-color": "*"

  "debug@*":
    dependencies:
      "supports-color": "*"

yarnPath: .yarn/releases/yarn-4.5.1.cjs
nodeLinker: pnp
pnpMode: loose
